version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-oidc-authing-demo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-kw8angxitdes"
s3_prefix = "aws-oidc-authing-demo"
region = "cn-northwest-1"
capabilities = "CAPABILITY_IAM"
