AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-oidc-authing-demo

  A simple demo for leveraging Authing.cn as a OIDC Identity Provider for AWS API Gateway
  @Author: Randy Lin
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  AuthingAppSecretParamter:
    Type: String
    Default: '****'
  AuthingRedirectURLParameter:
    Type: String
    Default: 'http://aws-oidc-authing-demo-codeflow.s3-website.cn-northwest-1.amazonaws.com.cn/'
  AuthingAppURLParameter : 
    Type: String
    Default: 'aws-oidc-authing-demo-codeflow'
  AuthingAppIDParameter :
    Type: String
    Default: '****'



Resources:

  # A Simple Demo API
  AWSOIDCAuthingApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: MyLambdaTokenAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          MyLambdaTokenAuthorizer:
            FunctionArn: !GetAtt LambdaAuthorizerFunction.Arn

  # A Simple demo function which is protected using Authing.cn
  ProtectedAPIFunction: 
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: protected-api/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        GetRoot:
          Type: Api 
          Properties:
            RestApiId: !Ref AWSOIDCAuthingApi
            Path: /info
            Method: get             

  # A Lambda Authorizer used by API Gateway to verify JWT issued from Authing
  LambdaAuthorizerFunction: 
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: lambda-authorizer/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Environment:
        Variables:
          Authing_App_Secret: !Ref AuthingAppSecretParamter
          Authing_Redirect_URL: !Ref AuthingRedirectURLParameter

      

  #Use Authorization Code to Exchange id token from Authing.cn (used by OIDC authorization code flow only)
  Code2IdtokenFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: code2idtoken/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Environment:
        Variables:
          Authing_App_URL : !Ref AuthingAppURLParameter
          Authing_App_ID :  !Ref AuthingAppIDParameter
          Authing_App_Secret: !Ref AuthingAppSecretParamter
          Authing_Redirect_URL: !Ref AuthingRedirectURLParameter
      Events:
        GetRoot:
          Type: Api
          Properties:
            RestApiId: !Ref AWSOIDCAuthingApi
            Path: /code2idtoken
            Method: get
            Auth:
              Authorizer: NONE

Outputs:

  AWSOIDCAuthingApi:
    Description: "API URL for Protected API function"
    Value: !Sub "https://${AWSOIDCAuthingApi}.execute-api.${AWS::Region}.amazonaws.com.cn/Prod/info"

  # AuthingHelperAPI:
  #   Description: "API URL for helper API to exchange id token using authorization code"
  #   Value: !Sub https://${AuthingHelperAPI}.execute-api.${AWS::Region}.amazonaws.com.cn/Prod/code2idtoken"
  
